# Generated by Django 2.2.7 on 2019-11-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flokkur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafn', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Flokkur',
                'verbose_name_plural': 'Flokkar',
            },
        ),
        migrations.CreateModel(
            name='Malsgrein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.TextField(unique=True)),
                ('mork', models.TextField()),
                ('flokkur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malsgreinar', to='frett.Flokkur')),
            ],
            options={
                'verbose_name': 'Málsgrein',
                'verbose_name_plural': 'Málsgreinar',
            },
        ),
    ]
