# Generated by Django 2.2.7 on 2019-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frett', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frett',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titill', models.CharField(blank=True, max_length=100, null=True)),
                ('html', models.TextField()),
                ('einstok_ord', models.TextField()),
            ],
            options={
                'verbose_name': 'Frétt',
                'verbose_name_plural': 'Fréttir',
            },
        ),
    ]
